Repository accordproject/cicero-ui, pull requests merged in 2019-05, with the labels that each got.

#23 chore(package): increment version for npm publish - I6
  package.json
Labels: good first issue

#29 feat(src): migrate contracteditor code - I1
  .babelrc
  CONTRIBUTING.md
  demo/src/index.html
  demo/src/index.js
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
  src/ContractEditor/commands/AddParsingErrorMark.js
  src/ContractEditor/commands/BadParse.js
  src/ContractEditor/commands/ConvertToHeaderChange.js
  src/ContractEditor/commands/ConvertToParagraphChange.js
  src/ContractEditor/commands/GoodParse.js
  src/ContractEditor/commands/RemoveErrorMark.js
  src/ContractEditor/commands/SetNodeData.js
  src/ContractEditor/commands/SetNodeDataByKey.js
  src/ContractEditor/commands/ToggleBlockTypeChange.js
  src/ContractEditor/components/BaseComponent.js
  src/ContractEditor/components/ClauseComponent.js
  src/ContractEditor/components/CustomLoader/index.js
  src/ContractEditor/components/TextBlock.js
  src/ContractEditor/index.js
  src/ContractEditor/index.test.js
  src/ContractEditor/plugins/ClauseParser.js
  src/ContractEditor/plugins/ClauseRenderer.js
  src/ContractEditor/plugins/clausePlugin.js
  src/ContractEditor/utilities/text.js
  src/index.js
Labels: enhancement

#38 docs(*): documentation for this repository - I37
  CONTRIBUTING.md
  DEVELOPERS.md
  LICENSE
  README.md
  markdown-license.txt
  src/ContractEditor/README.md
  src/TemplateLibrary/README.md
Labels: good first issue

#48 test(TemplateLibrary): implement test and fix proptypes - I-35
  package-lock.json
  src/ClauseEditor/__snapshots__/index.test.js.snap
  src/ClauseEditor/index.test.js
  src/ContractEditor/index.test.js
  src/ErrorLogger/index.test.js
  src/TemplateLibrary/TemplateActions.js
  src/TemplateLibrary/TemplateCard.js
  src/TemplateLibrary/__snapshots__/index.test.js.snap
  src/TemplateLibrary/index.js
  src/TemplateLibrary/index.test.js
  src/TemplateLoadingClauseEditor/__snapshots__/index.test.js.snap
  src/TemplateLoadingClauseEditor/index.test.js
Labels: bug, enhancement, good first issue

#50 fix(clausePlugin): fix toMarkdown to accommodate id attribute and add new lines before clause
  package-lock.json
  package.json
  src/ContractEditor/plugins/clausePlugin.js
  webpack.config.js
Labels: bug
