Repository accordproject/cicero-ui, pull requests merged in 2019-10, with the labels that each got.

#144 refactor(src): Font Size Change From px To em - I58
  package-lock.json
  package.json
  src/ErrorLogger/styles.js
  src/Navigation/styles.js
  src/TemplateLibrary/Buttons/index.js
  src/TemplateLibrary/TemplateActions.js
  src/TemplateLibrary/TemplateCard.js
  src/TemplateLibrary/index.js
  src/components/styles.js
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest, Type: Feature Request 🛍️

#148 fix(ErrorLogger): typo in errors check const name
  src/ErrorLogger/actions.js
  src/ErrorLogger/index.js
Labels: Difficulty: Starter, Hacktoberfest

#149 docs(README): add downloads badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#153 docs(README): fix typo
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#156 docs(README): add slack badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#161 docs(CONTRIBUTING): fix typos
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#162 fix(DEVELOPERS): correct typo to add main repository as upstream
  DEVELOPERS.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#163 fix(ClausePlugin): update last argument passed to parseClauseCallback to be clauseid
  src/plugins/ClausePlugin.js
Labels: Type: Bug 🐛

#164 fix(ClausePlugin): fix findClauseNode when getting clause id from node data
  src/plugins/ClausePlugin.js
Labels: Type: Bug 🐛

#165 feat(ErrorLogger): accept object instead array - I137
  src/ErrorLogger/Error.js
  src/ErrorLogger/README.md
  src/ErrorLogger/actions.js
  src/ErrorLogger/index.js
  src/ErrorLogger/index.test.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Enhancement ✨

#166 perf(TemplateLibrary): template library should use hooks issue done
  package-lock.json
  package.json
  src/TemplateLibrary/index.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Enhancement ✨

#169 fix(CONTRIBUTING): broken coc link - I168
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest

#171 feat(Security Vulnerability): removed yarn.lock
  package-lock.json
  yarn.lock
Labels: Difficulty: Starter, Good First Issue (Taken), Hacktoberfest

#175 docs(*): update markdown files and fix typos - I257
  CONTRIBUTING.md
  DEVELOPERS.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#174 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#173 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#172 docs(VariablePlugin): init docs - I146
  src/plugins/README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#177 test(ErrorLogger): init unit tests - I167
  src/ErrorLogger/Error.test.js
  src/ErrorLogger/__snapshots__/Error.test.js.snap
  src/ErrorLogger/__snapshots__/index.test.js.snap
  src/ErrorLogger/actions.test.js
  src/ErrorLogger/styles.js
Labels: Hacktoberfest, Type: Tests 🧪

#178 chore(package): increment markdown editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#185 fix(TemplateLibrary): Button styling
  package-lock.json
  package.json
  src/TemplateLibrary/Buttons/index.js
  src/styles.css
Labels: Difficulty: Starter, Hacktoberfest

#189 feat(ClausePlugin): implement debounce for parsing clause on change
  src/plugins/ClausePlugin.js
Labels: Type: Enhancement ✨

#192 chore(deps): update markdown editor dependency to 0.6.5
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#193 chore(*): increment markdown-editor
  package-lock.json
  package.json
  src/ContractEditor/index.js
Labels: Type: Dependencies 🏠

#198 fix(README): various
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#195 fix(README): grammar
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#204 fix(README): typo - I203
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#200 docs(README): plugins updates
  README.md
  src/ErrorLogger/README.md
  src/plugins/README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#205 test(Navigation): init unit tests - I123
  package.json
  src/Navigation/index.test.js
Labels: Difficulty: Starter, Hacktoberfest, Type: Tests 🧪

#197 test(ContractEditor): init unit test - I34
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
  src/ContractEditor/index.test.js
Labels: Difficulty: Challenging, Hacktoberfest, Type: Tests 🧪

#208 style(TemplateCard): make background of card default to white
  src/TemplateLibrary/TemplateCard.js
Labels: Difficulty: Starter
