Repository accordproject/cicero-ui, pull requests merged in 2019-06, with the labels that each got.

#59 fix(package): fix npm vulnerabilities
  package-lock.json
  package.json
Labels: bug, good first issue

#60 fix(ClauseComponent): fix casing for contentEditable prop
  src/components/ClauseComponent.js
Labels: bug

#64 chore(markdown-editor): bump markdown-editor dependency to 0.4.15
  package-lock.json
  package.json
  src/ClauseEditor/index.js
Labels: enhancement

#61 docs(*): update guidelines for contributions
  CONTRIBUTING.md
  DEVELOPERS.md
  LICENSE
  README.md
  assets/APLogo.png
Labels: enhancement

#66 feat(TemplateLibrary): adjust styling with conditionals - I62
  package-lock.json
  package.json
  src/TemplateLibrary/Buttons/index.js
  src/TemplateLibrary/TemplateCard.js
  src/TemplateLibrary/__snapshots__/index.test.js.snap
  src/TemplateLibrary/index.js
  src/TemplateLibrary/index.test.js
  src/TemplateLoadingClauseEditor/index.js
Labels: enhancement

#67 fix(ClauseComponent): fix getting clauseId from attributes
  package-lock.json
  src/ContractEditor/index.js
  src/plugins/ClausePlugin.js
Labels: bug

#68 fix(TemplateLibrary): remove margins for imports - I62
  src/TemplateLibrary/index.js
Labels: bug

#69 fix(TemplateLibrary): correct props declaration - I62
  src/TemplateLibrary/index.js
Labels: bug

#70 style(TemplateLibrary): adjust styling to remove margins - I62
  package-lock.json
  package.json
  src/TemplateLibrary/Buttons/index.js
  src/TemplateLibrary/TemplateCard.js
  src/TemplateLibrary/__snapshots__/index.test.js.snap
  src/TemplateLibrary/index.js
Labels: bug

#71 fix(TemplateLibrary): adjust paragraph css - I62
  src/TemplateLibrary/index.js
Labels: bug
