Repository accordproject/cicero-ui, pull requests merged in 2019-11, with the labels that each got.

#216 chore(package): increment markdown-editor
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
Labels: Type: Dependencies 🏠

#218 feat(plugins): allow markdown inside clause
  package-lock.json
  package.json
  src/plugins/ClausePlugin.js
Labels: Difficulty: Starter, Type: Enhancement ✨

#219 chore(package): increment markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#220 chore(deps): update markdown-editor to fix toolbar bug on locked text
  package-lock.json
  package.json
Labels: Type: Bug 🐛

#222 chore(package): increment markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#224 chore(package): increment markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#228 fix(ClausePlugin): use withMutations to fix issue when pasting a clause node
  src/plugins/ClausePlugin.js
Labels: Type: Bug 🐛

#235 fix(components): disallow edits to clause component - I139
  package-lock.json
  package.json
  src/components/ClauseComponent.js
  src/components/__snapshots__/index.test.js.snap
Labels: Difficulty: Medium, Type: Bug 🐛

#236 fix(VariablePlugin): call editor.moveToEndOfNode if extending a variable
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
  src/ContractEditor/index.test.js
  src/plugins/ClausePlugin.js
  src/plugins/ComputedPlugin.js
  src/plugins/VariablePlugin.js
Labels: Type: Bug 🐛

#190 fix(TemplateLibrary): Style for search box
  src/TemplateLibrary/index.js
  src/styles.css
Labels: Difficulty: Starter, Hacktoberfest
