Repository accordproject/cicero-ui, pull requests merged in 2020-05, with the labels that each got.

#402 refactor(template library): added fallback message if template list i…
  src/TemplateLibrary/index.js
Labels: Difficulty: Starter, Type: Enhancement ✨

#406 fix(ContractEditor): prevent fwd delete before clause - I403
  src/ContractEditor/index.js
  src/ContractEditor/plugins/withClauses.js
  src/ContractEditor/plugins/withVariables.js
Labels: Difficulty: Medium, Priority: High ⚠️, Slate v57 ⛰️, Type: Bug 🐛

#407 fix(withClauses): call pasteToContract from props
  src/ContractEditor/plugins/withClauses.js
Labels: Type: Bug 🐛

#409 chore(package): increment markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠
