Repository accordproject/cicero-ui, pull requests merged in 2020-02, with the labels that each got.

#277 fix(ClauseComponent): remove icons in read-only mode
  src/components/ClauseComponent.js
  src/plugins/ClausePlugin.js
Labels: Type: Bug 🐛

#281 fix(plugins): disallow deletion of entire variable - I280
  package-lock.json
  package.json
  src/plugins/VariablePlugin.js
Labels: 0.20-ui, Difficulty: Medium, Type: Bug 🐛

#291 feat(ErrorLogger): make Error Logger more resilient to missing error properties
  src/ErrorLogger/Error.js
Labels: Type: Bug 🐛

#292 fix(TemplateLibrary): fixed highlighting of text on selection in SeachInput - I269
  src/TemplateLibrary/index.js
Labels: A11Y 🔓, Difficulty: Starter, Type: Enhancement ✨

#298 style(src): improve clause components a11y - I57
  src/components/styles.js
  src/styles.css
Labels: A11Y 🔓, Difficulty: Starter, Type: Enhancement ✨

#306 fix(components): support safari for conditionals - I233
  package-lock.json
  package.json
  src/components/ConditionalBoolean.js
  src/components/ConditionalSwitch.js
  src/components/styles.js
  src/styles.css
Labels: 0.20-ui, Type: Bug 🐛

#308 chore(deps): Upgrade markdown-editor dependency to 0.9.8
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
Labels: Type: Dependencies 🏠

#305 RE: docs(README): updated and added the ConditionalPlugin
  src/plugins/README.md
Labels: Type: Documentation 📝
