Repository accordproject/cicero-ui, pull requests merged in 2020-03, with the labels that each got.

#321 test(components): add tests for titleGenerator & headerGenerator - #123
  src/components/index.test.js
Labels: Type: Tests 🧪

#323 style(ClauseTemplate): change ClauseTemplate background color - I322
  src/components/styles.js
Labels: A11Y 🔓, Difficulty: Starter, Type: Enhancement ✨

#326 chore(package): upgrade
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
Labels: Type: Dependencies 🏠

#327 chore(package): increment markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#331 chore(package): increment mde and resolve vulnerabilities
  package-lock.json
  package.json
  src/ContractEditor/__snapshots__/index.test.js.snap
Labels: Type: Dependencies 🏠

#332 docs(readme): Remove 404 links- I328
  README.md
Labels: Type: Bug 🐛, Type: Documentation 📝

#334 chore(package): inc mde
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#337 chore(package): inc mde
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#333 feat(Button): aria-label for Button accessibility -I55
  demo/src/index.js
  src/TemplateLibrary/Buttons/index.js
Labels: A11Y 🔓, Type: Enhancement ✨

#338 fix(styles.js): disables tooltip text selection - I330
  src/components/styles.js
Labels: Difficulty: Starter, Type: Bug 🐛

#343 chore(package): support for mde 9.15
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#347 feat(*): add background colors and borders to variables - I314
  src/components/ClauseComponent.js
  src/components/Conditional.js
  src/components/styles.js
  src/styles.css
Labels: 0.20-ui, Difficulty: Challenging, Type: Feature Request 🛍️

#350 fix(ConditionalPlugin) fixed feature allowing conitionals editing -I339
  src/plugins/ConditionalPlugin.js
Labels: Type: Bug 🐛

#348 feat(components) adding bulleted list variables -I230
  demo/src/index.js
  src/SlateCommands/RegenerateAllNodeKeys.js
  src/components/ClauseComponent.js
  src/components/ClauseVariableList.js
  src/components/styles.js
  src/icons/add.js
  src/icons/remove.js
  src/styles.css
Labels: 0.20-ui, Difficulty: Challenging, Type: Feature Request 🛍️

#349 docs(*): point PRs to development
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
Labels: Difficulty: Starter, Type: Documentation 📝

#353 feat(*): add storybook for developer focused demo - I315
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.js
  package-lock.json
  package.json
  src/stories/ContractEditor/ContractEditor.stories.js
  src/stories/ContractEditor/docs.md
  src/stories/ErrorLogger/ErrorLogger.stories.js
  src/stories/ErrorLogger/docs.md
Labels: Difficulty: Challenging, Type: Feature Request 🛍️
