Repository accordproject/cicero-ui, pull requests merged in 2020-04, with the labels that each got.

#366 feat(HeaderImport): fixed extra clickable area of import links
  src/TemplateLibrary/index.js
Labels: Type: Enhancement ✨

#367 refactor(docs): consolidate contribution guides
  CONTRIBUTING.md
  DEVELOPERS.md
Labels: Type: Documentation 📝

#369 doc(README) Add instructions for using the AP README badge
  README.md
Labels: Type: Documentation 📝

#394 chore(package): increment markdown packages - I378
  demo/src/index.js
  package-lock.json
  package.json
  src/ContractEditor/test/__snapshots__/index.test.js.snap
Labels: Slate57, Type: Dependencies 🏠

#395 feat(ContractEditor): add augmentEditor prop and update deps
  package-lock.json
  package.json
  src/ContractEditor/index.js
Labels: Type: Dependencies 🏠

#396 fix(Conditional): swap without normalizing - I392
  src/components/Conditional/index.js
Labels: Priority: High ⚠️, Slate57, Type: Bug 🐛

#397 fix(plugins): disable forward delete at end of variable - I374
  src/ContractEditor/plugins/withVariables.js
Labels: Priority: High ⚠️, Slate57

#398 chore(dep): update markdown-editor
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠
